# Generated by Django 2.0.9 on 2018-11-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20181122_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='decription',
            new_name='description',
        ),
    ]
