# Generated by Django 2.0.9 on 2018-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20181122_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='beat_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='beat_points',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='total_events',
            field=models.IntegerField(default=10),
        ),
    ]
