# Generated by Django 2.0.9 on 2018-11-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20181123_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='beat_events',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='beat_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points_events',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='total_events',
            field=models.IntegerField(),
        ),
    ]
