# Generated by Django 2.0.9 on 2018-11-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20181126_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='goal',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points_events',
            field=models.IntegerField(default=2),
        ),
    ]
