# Generated by Django 2.0.9 on 2018-11-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_auto_20181126_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='_porcent',
            field=models.IntegerField(default=100),
        ),
    ]
