# Generated by Django 2.0.9 on 2018-11-26 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_challenge__porcent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='_porcent',
            new_name='porcent',
        ),
    ]
