# Generated by Django 2.0.9 on 2018-11-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20181127_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='beat_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='porcent',
            field=models.IntegerField(),
        ),
    ]
