# Generated by Django 2.0.9 on 2018-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_auto_20181127_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='beat_events',
            field=models.IntegerField(default=0),
        ),
    ]
